[package]
name = "Zulu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
confy = "0.3.1"
ldap3 = "0.11.0-beta.1"
